var fs = require('fs');
var path = require('path');

var langsDir = path.join(__dirname, '..', 'js', 'lang');
var outputFile = path.join(__dirname, '..', 'js', 'i18n.js');

var langOrder = ['en', 'ar', 'zh', 'de', 'fr', 'ja', 'ru'];
var allData = {};

langOrder.forEach(function(l) {
    var filePath = path.join(langsDir, l + '.json');
    if (!fs.existsSync(filePath)) {
        console.error('Missing: ' + filePath);
        process.exit(1);
    }
    allData[l] = JSON.parse(fs.readFileSync(filePath, 'utf8'));
});

var lines = [];
lines.push('// ================================================================');
lines.push('// I18N — 7 Languages');
lines.push('// AUTO-GENERATED by scripts/build-i18n.js — DO NOT EDIT DIRECTLY');
lines.push('// Edit source files in js/lang/ instead and run: node scripts/build-i18n.js');
lines.push('// ================================================================');
lines.push('var I18N = {};');
lines.push('');

langOrder.forEach(function(l) {
    var data = allData[l];
    var keys = Object.keys(data);
    lines.push('I18N.' + l + ' = {');
    keys.forEach(function(k, i) {
        var val = data[k];
        var comma = i < keys.length - 1 ? ',' : '';
        lines.push('    ' + k + ':' + JSON.stringify(val) + comma);
    });
    lines.push('};');
    lines.push('');
});

lines.push('var currentLang = localStorage.getItem(\'smartlap_lang\') || \'en\';');
lines.push('');
lines.push('function setLang(lang) {');
lines.push('    currentLang = lang;');
lines.push('    localStorage.setItem(\'smartlap_lang\', lang);');
lines.push('    var isRtl = (lang === \'ar\');');
lines.push('    document.documentElement.dir = isRtl ? \'rtl\' : \'ltr\';');
lines.push('    document.documentElement.lang = lang;');
lines.push('    document.documentElement.setAttribute(\'data-dir\', isRtl ? \'rtl\' : \'ltr\');');
lines.push('    document.body.setAttribute(\'data-dir\', isRtl ? \'rtl\' : \'ltr\');');
lines.push('    var t = I18N[lang] || I18N.en;');
lines.push('    document.querySelectorAll(\'[data-i18n]\').forEach(function(el) {');
lines.push('        var key = el.getAttribute(\'data-i18n\');');
lines.push('        if (t[key]) el.textContent = t[key];');
lines.push('    });');
lines.push('    document.querySelectorAll(\'[data-i18n-ph]\').forEach(function(el) {');
lines.push('        var key = el.getAttribute(\'data-i18n-ph\');');
lines.push('        if (t[key]) el.placeholder = t[key];');
lines.push('    });');
lines.push('    var sel = document.getElementById(\'lang-select\');');
lines.push('    if (sel) sel.value = lang;');
lines.push('    var sel2 = document.getElementById(\'lang-select2\');');
lines.push('    if (sel2) sel2.value = lang;');
lines.push('}');
lines.push('');
lines.push('function applyDirection() {');
lines.push('    var isRtl = currentLang === \'ar\';');
lines.push('    document.documentElement.dir = isRtl ? \'rtl\' : \'ltr\';');
lines.push('    document.documentElement.setAttribute(\'data-dir\', isRtl ? \'rtl\' : \'ltr\');');
lines.push('    document.body.setAttribute(\'data-dir\', isRtl ? \'rtl\' : \'ltr\');');
lines.push('}');
lines.push('');
lines.push('var dirObserver = new MutationObserver(function(mutations) {');
lines.push('    mutations.forEach(function(mutation) {');
lines.push('        mutation.addedNodes.forEach(function(node) {');
lines.push('            if (node.nodeType === 1 && !node.hasAttribute(\'data-dir\')) {');
lines.push('                node.setAttribute(\'data-dir\', currentLang === \'ar\' ? \'rtl\' : \'ltr\');');
lines.push('            }');
lines.push('        });');
lines.push('    });');
lines.push('});');
lines.push('dirObserver.observe(document.documentElement, { childList: true, subtree: true });');
lines.push('');

fs.writeFileSync(outputFile, lines.join('\n'), 'utf8');
console.log('Generated: ' + outputFile);
console.log('Languages: ' + langOrder.join(', '));
console.log('Total keys: ' + Object.keys(allData.en).length);
